name: GenerateChangelogAndCreatePR
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: changelog-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changelog
        run: |
          BRANCH_NAME="auto/changelog-update"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -B "$BRANCH_NAME"
          git add CHANGELOG.md
          git commit -m "chore: Update changelog [skip ci]" || echo "No changes to commit"
          git push -f origin "$BRANCH_NAME"

      - name: Create PR and enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head auto/changelog-update \
            --title "chore: Automated Changelog Update" \
            --body "Auto-generated changelog update." || echo "PR already exists"
          
          PR_URL=$(gh pr view auto/changelog-update --json url -q .url)
          gh pr merge "$PR_URL" --auto --squash || echo "Auto-merge already enabled"