name: GenerateChangelogAndCreatePR
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'release/**'
  workflow_dispatch:
concurrency:
  group: changelog-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout "${{ github.head_ref }}"
          git add CHANGELOG.md
          git commit -m "chore: Update changelog [skip ci]" || echo "No changes to commit"
          git push origin "${{ github.head_ref }}"