name: GenerateChangelogAndCreatePR
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
concurrency:
  group: changelog-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  changelog:
    name: Generate changelog and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
      - name: Commit and push changelog
        uses: EndBug/add-and-commit@v9.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: CHANGELOG.md
          message: "chore: Update CHANGELOG.md"
          branch: main