name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: startsWith(github.head_ref || github.ref_name, 'release/')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git-cliff to access full history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: ./cliff.toml
          args: --tag HEAD --output CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push

      - name: Extract version from branch name
        id: version
        run: echo "version=${GITHUB_REF_NAME#release-}" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.version }}"