name: Release


on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    if: startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Update version
        id: set_version
        run: |
          version="v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: ./cliff.toml
          args: --tag ${{ env.VERSION }}
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push version + changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.event.pull_request.head.ref }}
          git pull origin ${{ github.event.pull_request.head.ref }}
          git add CHANGELOG.md
          git commit -m "chore: release v${{ env.VERSION }}"
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Create Git tag
        run: |
          git tag -a "${{ env.VERSION }}" -m "Release ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"