name: container project - release build

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pages: write
    steps:
      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: outputs

      # - name: Verify artifacts exist
      #   run: |
      #     echo "Checking for expected artifacts..."
      #     ls -la outputs/container-package/
      #     test -e outputs/container-package/*.zip || (echo "Missing .zip file!" && exit 1)
      #     test -e outputs/container-package/*.pkg || (echo "Missing .pkg file!" && exit 1)

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          name: ${{ github.ref_name }}
          draft: false
          make_latest: true
          prerelease: false
          fail_on_unmatched_files: true
          # files: |
          #   outputs/container-package/*.zip
          #   outputs/container-package/*.pkg
